// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjqmcgykutxazuaksjtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqcW1jZ3lrdXR4YXp1YWtzanRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NTQzODUsImV4cCI6MjA1OTQzMDM4NX0.fIElnLLKz5VjDg8VP-smmMvjDSisqMQyFmSWF3Qe9g4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);